services:
  orchestrator:
    build:
      context: .
      dockerfile: containers/orchestrator/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - LOG_LEVEL=INFO