services:
  sbom-platform:
    build: .
    ports:
      - "8000:8000"    # Main API
      - "9876:9876"    # Telemetry server
    volumes:
      - ./data:/app/data
      - ./telemetry_data:/app/telemetry_data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    networks:
      - sbom-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sbom-network:
    driver: bridge

volumes:
  telemetry_data:
  logs: