services:
  sbom-platform:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    ports:
      - "8080:8000"    # Main API
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3