/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package _int.nato.ncia.natxmlib.gui;

import _int.nato.ncia.natxmlib.test.MIDSGateway;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author mike
 */
public class MIDSGatewayGUI extends javax.swing.JFrame {
    protected final MIDSGateway midsGateway;
    
    public MIDSGatewayGUI(MIDSGateway midsGateway) {
        
        this.midsGateway=midsGateway;
        initComponents();
        updateUI();
        Timer t=new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateUI();
            }
        });
        t.setRepeats(true);
        t.start();
        
    }
    protected final void updateUI() {
        this.tfSyncStatus.setText(midsGateway.controller.syncState());
        this.tfInitStatus.setText(midsGateway.controller.initState());
        this.tfTerminalTime.setText(midsGateway.controller.getTerminalTime());
        this.tfTerminalDate.setText(midsGateway.controller.getTerminalDate());
        this.tfTerminalStatus.setText(midsGateway.controller.terminalConnectionStatus());
        this.tfMTOD.setText(midsGateway.controller.midsTOD());
        this.tfChronoTime.setText(midsGateway.controller.chronoTime());
        this.cbIsNTR.setSelected(midsGateway.controller.isNTR());
        this.cbIsETR.setSelected(midsGateway.controller.isETR());
        this.cbIsETROK.setSelected(midsGateway.controller.isETROK());
        this.cbTimeOK.setSelected(midsGateway.controller.isMIDSTimeOK());
        this.tfUTCTime.setText(midsGateway.controller.getUTCTime());
        this.tfUTCDate.setText(midsGateway.controller.getUTCDate());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnResetInitData = new javax.swing.JButton();
        btnRestartLoadDefaults = new javax.swing.JButton();
        btnRestartLoadCurrent = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tfSyncStatus = new javax.swing.JTextField();
        tfInitStatus = new javax.swing.JTextField();
        tfTerminalTime = new javax.swing.JTextField();
        tfTerminalStatus = new javax.swing.JTextField();
        tfUTCDate = new javax.swing.JTextField();
        cbIsETR = new javax.swing.JCheckBox();
        cbIsNTR = new javax.swing.JCheckBox();
        cbIsETROK = new javax.swing.JCheckBox();
        cbTimeOK = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        tfMTOD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfChronoTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfUTCTime = new javax.swing.JTextField();
        tfTerminalDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbNTR = new javax.swing.JCheckBox();
        cbETR = new javax.swing.JCheckBox();
        btnNetEntryReset = new javax.swing.JButton();
        cbTimeSync = new javax.swing.JCheckBox();
        cbStartNetEntry = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JTIDS MIDS Gateway");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnResetInitData.setText("Reset Initialization Data");
        btnResetInitData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetInitDataActionPerformed(evt);
            }
        });

        btnRestartLoadDefaults.setText("Restart Load (default)");
        btnRestartLoadDefaults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartLoadDefaultsActionPerformed(evt);
            }
        });

        btnRestartLoadCurrent.setText("Restart Load (current)");
        btnRestartLoadCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartLoadCurrentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRestartLoadCurrent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRestartLoadDefaults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResetInitData, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnResetInitData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRestartLoadDefaults)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRestartLoadCurrent)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tfSyncStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSyncStatusActionPerformed(evt);
            }
        });

        tfInitStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInitStatusActionPerformed(evt);
            }
        });

        tfTerminalTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTerminalTimeActionPerformed(evt);
            }
        });

        tfTerminalStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTerminalStatusActionPerformed(evt);
            }
        });

        tfUTCDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUTCDateActionPerformed(evt);
            }
        });

        cbIsETR.setText("is ETR");
        cbIsETR.setEnabled(false);

        cbIsNTR.setText("is NTR");
        cbIsNTR.setEnabled(false);

        cbIsETROK.setText("ETR OK");
        cbIsETROK.setEnabled(false);

        cbTimeOK.setText("Time OK");
        cbTimeOK.setEnabled(false);

        jLabel1.setText("TTOD");

        tfMTOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMTODActionPerformed(evt);
            }
        });

        jLabel2.setText("MTOD");

        tfChronoTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChronoTimeActionPerformed(evt);
            }
        });

        jLabel3.setText("CTIME");

        tfUTCTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUTCTimeActionPerformed(evt);
            }
        });

        tfTerminalDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTerminalDateActionPerformed(evt);
            }
        });

        jLabel4.setText("UTC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbTimeOK)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfInitStatus, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSyncStatus, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTerminalStatus, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(cbIsNTR)
                                .addGap(18, 18, 18)
                                .addComponent(cbIsETR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbIsETROK))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tfTerminalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfTerminalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tfUTCTime, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfUTCDate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfMTOD)
                                    .addComponent(tfChronoTime))))
                        .addGap(257, 257, 257))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tfTerminalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfInitStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tfSyncStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfUTCTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfUTCDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTerminalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tfTerminalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMTOD, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfChronoTime, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbIsNTR)
                    .addComponent(cbIsETR)
                    .addComponent(cbIsETROK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTimeOK)
                .addGap(49, 49, 49))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbNTR.setText("NTR");

        cbETR.setText("ETR");

        btnNetEntryReset.setText("Net Entry Reset");
        btnNetEntryReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetEntryResetActionPerformed(evt);
            }
        });

        cbTimeSync.setText("TIME SYNC");

        cbStartNetEntry.setSelected(true);
        cbStartNetEntry.setText("START NET ENTRY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbETR)
                            .addComponent(cbNTR))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTimeSync)
                            .addComponent(cbStartNetEntry)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnNetEntryReset, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNTR)
                    .addComponent(cbTimeSync))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbETR)
                    .addComponent(cbStartNetEntry))
                .addGap(26, 26, 26)
                .addComponent(btnNetEntryReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetInitDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetInitDataActionPerformed
        midsGateway.controller.doResetLoad();
    }//GEN-LAST:event_btnResetInitDataActionPerformed

    private void btnRestartLoadDefaultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartLoadDefaultsActionPerformed
        midsGateway.controller.doRestartLoad(true);
    }//GEN-LAST:event_btnRestartLoadDefaultsActionPerformed

    private void btnRestartLoadCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartLoadCurrentActionPerformed
        midsGateway.controller.doRestartLoad(false);
    }//GEN-LAST:event_btnRestartLoadCurrentActionPerformed

    private void tfSyncStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSyncStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSyncStatusActionPerformed

    private void tfInitStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInitStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInitStatusActionPerformed

    private void btnNetEntryResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetEntryResetActionPerformed
        midsGateway.controller.doNetEntryReset(cbNTR.isSelected(), cbETR.isSelected(), cbTimeSync.isSelected(), cbStartNetEntry.isSelected());
    }//GEN-LAST:event_btnNetEntryResetActionPerformed

    private void tfTerminalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTerminalTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTerminalTimeActionPerformed

    private void tfTerminalStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTerminalStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTerminalStatusActionPerformed

    private void tfUTCDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUTCDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUTCDateActionPerformed

    private void tfMTODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMTODActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMTODActionPerformed

    private void tfChronoTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChronoTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChronoTimeActionPerformed

    private void tfUTCTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUTCTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUTCTimeActionPerformed

    private void tfTerminalDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTerminalDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTerminalDateActionPerformed

    /**
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MIDSGatewayGUI().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNetEntryReset;
    private javax.swing.JButton btnResetInitData;
    private javax.swing.JButton btnRestartLoadCurrent;
    private javax.swing.JButton btnRestartLoadDefaults;
    private javax.swing.JCheckBox cbETR;
    private javax.swing.JCheckBox cbIsETR;
    private javax.swing.JCheckBox cbIsETROK;
    private javax.swing.JCheckBox cbIsNTR;
    private javax.swing.JCheckBox cbNTR;
    private javax.swing.JCheckBox cbStartNetEntry;
    private javax.swing.JCheckBox cbTimeOK;
    private javax.swing.JCheckBox cbTimeSync;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfChronoTime;
    private javax.swing.JTextField tfInitStatus;
    private javax.swing.JTextField tfMTOD;
    private javax.swing.JTextField tfSyncStatus;
    private javax.swing.JTextField tfTerminalDate;
    private javax.swing.JTextField tfTerminalStatus;
    private javax.swing.JTextField tfTerminalTime;
    private javax.swing.JTextField tfUTCDate;
    private javax.swing.JTextField tfUTCTime;
    // End of variables declaration//GEN-END:variables
}
