# Telemetry Agent Configuration (Final Fixed Version)

# Server connection settings
server:
  host: 10.211.55.2  # Your Docker host IP
  port: 9876

# Agent settings
agent:
  # Unique agent ID (leave empty to auto-generate)
  # id: "my-server-01"
  
  # Heartbeat interval in seconds
  heartbeat_interval: 60

# Collection settings
collection:
  # How often to collect BOM data (in seconds)
  interval: 3600  # 1 hour
  
  # Whether to perform deep scan (all packages)
  deep_scan: false
  
  # Collection timeout (in seconds)
  timeout: 300

# Logging settings
logging:
  level: INFO
  file: telemetry-agent.log
